name: "Python: Test and lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Test on ${{ matrix.python }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install Python interpreter
        run: uv python install ${{ matrix.python }}
      - uses: pre-commit/action@v3.0.1
      - run: uv sync --all-extras --dev
      - name: Run osswiz repo-review rules (smoke test)
        continue-on-error: true
        run: uv run --dev repo-review --select LIC
      - name: Execute python tests
        run: uv run pytest -s
